# .scrutinizer.yml
build:
    environment:
        php:
          version: '7.1.12'
    dependencies:
        before:
            - cp composer.json.dist composer.json
            - composer install
    project_setup:
        override: true
    tests:
        override: [php-scrutinizer-run]
filter:
    excluded_paths:
        - "tests/*"
    dependency_paths:
        - "vendor/"
tools:
    external_code_coverage:
        timeout: 1800   # Timeout in seconds.
        runs: 1         # Scrutinizer will wait for n code coverage submissions
