sudo: false

language: php

php:
  - 7.1
  - 7.2
  - 7.3
#  - 7.4snapshot

#matrix:
#  allow_failures:
#    - php: 7.4snapshot

before_install:
  - composer self-update

install:
  - composer install

script:
  - xoops_lib/vendor/bin/phpunit

after_script:
  - if [ "$TRAVIS_PHP_VERSION" != "7.4snapshot" ] && [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" != "7.4snapshot" ] && [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
